### ISSUE TITLE
Unable to build against MyNewt 1.7.0rc2

### ISSUE THREAD

**Issue by jeremywood** [hathach/mynewt-tinyusb-example#4]
I'm getting the following build error when trying to build on MyNewt 1.7:

```
Error: In file included from repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/include/nrfx_power.h:37:0,
                 from apps/cdc_msc_hid/src/main.c:38:
repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/include/nrfx_power_clock.h:58:6: error: #error "This code is not supposed to be compiled when neither POWER nor CLOCK is enabled."
     #error "This code is not supposed to be compiled when neither POWER nor CLOCK is enabled."
      ^~~~~
```

Reproduce by changing the mynewt repo to 1.7.0rc2.

**Comment by hathach** [comment]
Thanks for reporting this, I will check it out

**Comment by hathach** [comment]
give it a try but couldn't upgrade the repo due to the newt tool 1.7 is not released yet. I will try again later when it comes out.

```
Making the following changes to the project:
    upgrade apache-mynewt-core (1.6.0 --> 1.7.0)
    upgrade apache-mynewt-nimble (1.1.0 --> 1.2.0)
    upgrade mcuboot (0.0.0 --> 1.3.1)
Error: This version of newt (1.6.0) is incompatible with your version of the apache-mynewt-core repo (1.7.0); Please upgrade your newt tool to version 1.7.0
This version of newt (1.6.0) is incompatible with your version of the apache-mynewt-nimble repo (1.2.0); Please upgrade your newt tool to version 1.7.0
```
